plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version '3.5.13'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'io.mopl'
version = '0.0.1-SNAPSHOT'
description = 'sb09-mopl-team01'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven {
        url = uri('https://packages.confluent.io/maven/')
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'io.confluent:kafka-json-schema-serializer:7.9.1'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'
    runtimeOnly 'com.h2database:h2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
    // env
    implementation 'me.paulschwarz:spring-dotenv:4.0.0'

    //QueryDSL
    implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
    annotationProcessor 'com.querydsl:querydsl-apt:5.0.0:jakarta'
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'

    // AWS
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-s3:3.1.1'

    // Spring-Batch
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    testImplementation 'org.springframework.batch:spring-batch-test'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // Spring Security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'com.nimbusds:nimbus-jose-jwt:10.3'
    implementation 'org.springframework.security:spring-security-messaging'

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // SMTP
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // MIME
    implementation 'org.apache.tika:tika-core:3.0.0'

    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    
    // OAuth2
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    // AWS SecretManager
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-secrets-manager:3.0.1'

    // OpenSearch
    implementation 'org.opensearch.client:spring-data-opensearch-starter:1.7.0'

    // Redisson
    implementation 'org.redisson:redisson-spring-boot-starter:3.27.0'
}

jacoco {
    toolVersion = '0.8.13'
}

def jacocoExclusions = [
        "**/dto/**",
        "**/entity/**",
        "**/exception/**",
        "**/mapper/**"
]

def filteredJacocoClassDirectories = { directories ->
    files(directories.files.collect {
        fileTree(dir: it, exclude: jacocoExclusions)
    })
}

test {
    ignoreFailures = false
    useJUnitPlatform()
    systemProperty 'spring.profiles.active', 'test'
    finalizedBy jacocoTestReport
}


jacocoTestReport {
    dependsOn test

    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }

    afterEvaluate {
        classDirectories.setFrom(filteredJacocoClassDirectories(classDirectories))
    }
}

jacocoTestCoverageVerification {
    dependsOn jacocoTestReport

    afterEvaluate {
        classDirectories.setFrom(filteredJacocoClassDirectories(classDirectories))
    }

    violationRules {
        rule {
            limit {
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = 0.80
            }
        }
    }
}

check.dependsOn jacocoTestCoverageVerification
