spring:
  application:
    name: mopl
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true
  batch:
    jdbc:
      initialize-schema: never

  jackson:
    serialization:
      write-dates-as-timestamps: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true


jwt:
  # 향후 env로 옮길 예정
  secret: bXktand0LXNlY3JldC1rZXktZm9yLXNwcmluZy1zZWN1cml0eQ==
  #
  access-token-validity-seconds: 3600
  refresh-token-validity-seconds: 604800

mopl:
  # 향후 env로 옮길 예정
  admin:
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@mopl.com}
    password: ${ADMIN_PASSWORD:admin1234}
  #