server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

spring:
  config:
    import: "aws-secretsmanager:mopl-prod-secrets"

  datasource:
    url: jdbc:postgresql://${RDS_HOST}:${RDS_PORT:5432}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:true}

  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_API_KEY:}" password="${KAFKA_API_SECRET:}";'
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: "${KAFKA_SCHEMA_REGISTRY_API_KEY:}:${KAFKA_SCHEMA_REGISTRY_API_SECRET:}"
      auto.register.schemas: false

management:
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState,ping
        readiness:
          include: readinessState,db
