spring:
#  config:
#    import:
#      - classpath:application-local-h2.yml
  datasource:
    url: jdbc:postgresql://${RDS_HOST:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:postgres}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:Moplteam01!}
    driver-class-name: org.postgresql.Driver

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${CLOUD_AWS_REGION_STATIC:ap-northeast-2}
      s3:
        bucket: ${CLOUD_AWS_S3_BUCKET}

  # .env 파일로 옮겨야함
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:admin1234}

  file:
    upload-dir: ./uploads/images